// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYyo344Fw_sEBMBIHbWDF9A3PeUmHHxJA',
    appId: '1:676760477520:web:4e983f201dc1cdc1659655',
    messagingSenderId: '676760477520',
    projectId: 'fir-with-app-f58c9',
    authDomain: 'fir-with-app-f58c9.firebaseapp.com',
    storageBucket: 'fir-with-app-f58c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsaw-W7jXtZRNHs_isDFtVA9-Di4_fQ8',
    appId: '1:676760477520:android:91461745f699089d659655',
    messagingSenderId: '676760477520',
    projectId: 'fir-with-app-f58c9',
    storageBucket: 'fir-with-app-f58c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qlKD4_miuR3S7KiJxhrZ-8U420-EV_g',
    appId: '1:676760477520:ios:7b462dc9c1e3b662659655',
    messagingSenderId: '676760477520',
    projectId: 'fir-with-app-f58c9',
    storageBucket: 'fir-with-app-f58c9.appspot.com',
    iosBundleId: 'com.example.appwithfirebase',
  );
}
